# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ThirtySix\PycharmProjects\organization\package\ui\modMonUI.ui'
#
# Created: Tue Mar 15 21:32:38 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(879, 824)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.curvewidget = CurveWidget(self.centralwidget)
        self.curvewidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.curvewidget.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget.setObjectName(_fromUtf8("curvewidget"))
        self.verticalLayout_3.addWidget(self.curvewidget)
        self.Slider = Qwt5.QwtSlider(self.centralwidget)
        self.Slider.setReadOnly(False)
        self.Slider.setScalePosition(Qwt5.QwtSlider.BottomScale)
        self.Slider.setBgStyle(Qwt5.QwtSlider.BgSlot)
        self.Slider.setObjectName(_fromUtf8("Slider"))
        self.verticalLayout_3.addWidget(self.Slider)
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_3.addWidget(self.line_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setMinimum(100)
        self.dial.setMaximum(5000)
        self.dial.setSingleStep(10)
        self.dial.setProperty("value", 1000)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayout_7.addWidget(self.dial)
        self.timerLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timerLabel.setFont(font)
        self.timerLabel.setObjectName(_fromUtf8("timerLabel"))
        self.verticalLayout_7.addWidget(self.timerLabel)
        self.sampleIntervalDial = QtGui.QDial(self.centralwidget)
        self.sampleIntervalDial.setMinimum(10)
        self.sampleIntervalDial.setMaximum(1002)
        self.sampleIntervalDial.setNotchTarget(100.0)
        self.sampleIntervalDial.setNotchesVisible(True)
        self.sampleIntervalDial.setObjectName(_fromUtf8("sampleIntervalDial"))
        self.verticalLayout_7.addWidget(self.sampleIntervalDial)
        self.timerLabel_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timerLabel_2.setFont(font)
        self.timerLabel_2.setObjectName(_fromUtf8("timerLabel_2"))
        self.verticalLayout_7.addWidget(self.timerLabel_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_4.addWidget(self.line_4)
        self.timerStatusLabel = QtGui.QLabel(self.centralwidget)
        self.timerStatusLabel.setObjectName(_fromUtf8("timerStatusLabel"))
        self.verticalLayout_4.addWidget(self.timerStatusLabel)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout_4.addWidget(self.line_8)
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        self.timeLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.timeLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.timeLabel.setLineWidth(1)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.verticalLayout_4.addWidget(self.timeLabel)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_4.addWidget(self.line_5)
        self.svLabel = QtGui.QLabel(self.centralwidget)
        self.svLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.svLabel.setObjectName(_fromUtf8("svLabel"))
        self.verticalLayout_4.addWidget(self.svLabel)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_4.addWidget(self.line_7)
        self.pvLabel = QtGui.QLabel(self.centralwidget)
        self.pvLabel.setObjectName(_fromUtf8("pvLabel"))
        self.verticalLayout_4.addWidget(self.pvLabel)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/gtk-media-play-ltr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout_4.addWidget(self.startButton)
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/editdelete.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetButton.setIcon(icon1)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.verticalLayout_4.addWidget(self.resetButton)
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/gtk-media-stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.verticalLayout_4.addWidget(self.stopButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_9 = QtGui.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalSlider.setMaximum(9999)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.verticalLayout_5.addWidget(self.verticalSlider)
        self.SvLcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.SvLcdNumber.setSmallDecimalPoint(False)
        self.SvLcdNumber.setNumDigits(5)
        self.SvLcdNumber.setProperty("value", 999.9)
        self.SvLcdNumber.setObjectName(_fromUtf8("SvLcdNumber"))
        self.verticalLayout_5.addWidget(self.SvLcdNumber)
        self.setSvButton = QtGui.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/1uparrow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setSvButton.setIcon(icon3)
        self.setSvButton.setObjectName(_fromUtf8("setSvButton"))
        self.verticalLayout_5.addWidget(self.setSvButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.connectionTab_2 = QtGui.QWidget()
        self.connectionTab_2.setObjectName(_fromUtf8("connectionTab_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.connectionTab_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.portComboBox = QtGui.QComboBox(self.connectionTab_2)
        self.portComboBox.setObjectName(_fromUtf8("portComboBox"))
        self.gridLayout_3.addWidget(self.portComboBox, 0, 0, 1, 1)
        self.baudComboBox = QtGui.QComboBox(self.connectionTab_2)
        self.baudComboBox.setObjectName(_fromUtf8("baudComboBox"))
        self.baudComboBox.addItem(_fromUtf8(""))
        self.baudComboBox.addItem(_fromUtf8(""))
        self.baudComboBox.addItem(_fromUtf8(""))
        self.baudComboBox.addItem(_fromUtf8(""))
        self.baudComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.baudComboBox, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.connectionTab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.connectionTab_2)
        self.label_14.setWordWrap(False)
        self.label_14.setMargin(0)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.dataBitsComboBox = QtGui.QComboBox(self.connectionTab_2)
        self.dataBitsComboBox.setObjectName(_fromUtf8("dataBitsComboBox"))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.dataBitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.dataBitsComboBox, 1, 3, 1, 1)
        self.ParityComboBox = QtGui.QComboBox(self.connectionTab_2)
        self.ParityComboBox.setObjectName(_fromUtf8("ParityComboBox"))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ParityComboBox, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.connectionTab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.stopBitsComboBox = QtGui.QComboBox(self.connectionTab_2)
        self.stopBitsComboBox.setObjectName(_fromUtf8("stopBitsComboBox"))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.stopBitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.stopBitsComboBox, 1, 1, 1, 1)
        self.connectButton = QtGui.QPushButton(self.connectionTab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(165, 240, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 240, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(165, 240, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.connectButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.connectButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/tool_logwindow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon4)
        self.connectButton.setFlat(False)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.gridLayout_3.addWidget(self.connectButton, 3, 3, 1, 1)
        self.timoutDoubleSpinBox = QtGui.QDoubleSpinBox(self.connectionTab_2)
        self.timoutDoubleSpinBox.setDecimals(1)
        self.timoutDoubleSpinBox.setMaximum(1.0)
        self.timoutDoubleSpinBox.setProperty("value", 0.1)
        self.timoutDoubleSpinBox.setObjectName(_fromUtf8("timoutDoubleSpinBox"))
        self.gridLayout_3.addWidget(self.timoutDoubleSpinBox, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.connectionTab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/USBcable.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.connectionTab_2, icon5, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.lcdNumber = QtGui.QLCDNumber(self.tab_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(231, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdNumber.setPalette(palette)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setProperty("value", 999.9)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.verticalLayout.addWidget(self.lcdNumber)
        self.getPvButton = QtGui.QPushButton(self.tab_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/1downarrow.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getPvButton.setIcon(icon6)
        self.getPvButton.setObjectName(_fromUtf8("getPvButton"))
        self.verticalLayout.addWidget(self.getPvButton)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.tab_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 222, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdNumber_2.setPalette(palette)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setProperty("value", 999.9)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.getSvButton = QtGui.QPushButton(self.tab_5)
        self.getSvButton.setIcon(icon6)
        self.getSvButton.setObjectName(_fromUtf8("getSvButton"))
        self.verticalLayout_2.addWidget(self.getSvButton)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/Analyzeloop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon7, _fromUtf8(""))
        self.monitorTab_2 = QtGui.QWidget()
        self.monitorTab_2.setObjectName(_fromUtf8("monitorTab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.monitorTab_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.dataTextEdit = QtGui.QTextEdit(self.monitorTab_2)
        self.dataTextEdit.setObjectName(_fromUtf8("dataTextEdit"))
        self.horizontalLayout_7.addWidget(self.dataTextEdit)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/Bill.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.monitorTab_2, icon8, _fromUtf8(""))
        self.dataTab_2 = QtGui.QWidget()
        self.dataTab_2.setObjectName(_fromUtf8("dataTab_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.dataTab_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.DaqTableWidget = QtGui.QTableWidget(self.dataTab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DaqTableWidget.sizePolicy().hasHeightForWidth())
        self.DaqTableWidget.setSizePolicy(sizePolicy)
        self.DaqTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.DaqTableWidget.setObjectName(_fromUtf8("DaqTableWidget"))
        self.DaqTableWidget.setColumnCount(6)
        self.DaqTableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.DaqTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.DaqTableWidget.setItem(0, 5, item)
        self.DaqTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.DaqTableWidget.horizontalHeader().setMinimumSectionSize(2)
        self.DaqTableWidget.horizontalHeader().setStretchLastSection(False)
        self.DaqTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.DaqTableWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.dataTab_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.label_3 = QtGui.QLabel(self.dataTab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/Research.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.dataTab_2, icon9, _fromUtf8(""))
        self.modbusTab_2 = QtGui.QWidget()
        self.modbusTab_2.setObjectName(_fromUtf8("modbusTab_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.modbusTab_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.modbusTab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_17 = QtGui.QLabel(self.modbusTab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.PvReadSpinBox = QtGui.QSpinBox(self.modbusTab_2)
        self.PvReadSpinBox.setMaximum(10000)
        self.PvReadSpinBox.setProperty("value", 4096)
        self.PvReadSpinBox.setObjectName(_fromUtf8("PvReadSpinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.PvReadSpinBox)
        self.label_18 = QtGui.QLabel(self.modbusTab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.SvReadSpinBox = QtGui.QSpinBox(self.modbusTab_2)
        self.SvReadSpinBox.setMaximum(10000)
        self.SvReadSpinBox.setProperty("value", 4097)
        self.SvReadSpinBox.setObjectName(_fromUtf8("SvReadSpinBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.SvReadSpinBox)
        self.label_19 = QtGui.QLabel(self.modbusTab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_19)
        self.PvWriteSpinBox = QtGui.QSpinBox(self.modbusTab_2)
        self.PvWriteSpinBox.setMaximum(10000)
        self.PvWriteSpinBox.setProperty("value", 4096)
        self.PvWriteSpinBox.setObjectName(_fromUtf8("PvWriteSpinBox"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.PvWriteSpinBox)
        self.label_20 = QtGui.QLabel(self.modbusTab_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_20)
        self.SvWriteSpinBox = QtGui.QSpinBox(self.modbusTab_2)
        self.SvWriteSpinBox.setMaximum(10000)
        self.SvWriteSpinBox.setProperty("value", 4097)
        self.SvWriteSpinBox.setObjectName(_fromUtf8("SvWriteSpinBox"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.SvWriteSpinBox)
        self.label_5 = QtGui.QLabel(self.modbusTab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout_13.addLayout(self.formLayout_2)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/PCboard.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.modbusTab_2, icon10, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/application-exit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon11)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave_Data = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/stock_save.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Data.setIcon(icon12)
        self.actionSave_Data.setObjectName(_fromUtf8("actionSave_Data"))
        self.actionReset_DAQ = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/gtk-refresh.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_DAQ.setIcon(icon13)
        self.actionReset_DAQ.setObjectName(_fromUtf8("actionReset_DAQ"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/help-about.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon14)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/gnome-help.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon15)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuFile.addAction(self.actionSave_Data)
        self.menuFile.addAction(self.actionReset_DAQ)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionReset_DAQ)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_Data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.baudComboBox.setCurrentIndex(2)
        self.dataBitsComboBox.setCurrentIndex(1)
        self.ParityComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.timerLabel.setText(_translate("MainWindow", "Plotting Interval: 1000", None))
        self.timerLabel_2.setText(_translate("MainWindow", "Sample Interval: 100", None))
        self.timerStatusLabel.setText(_translate("MainWindow", "Status: Stopped", None))
        self.timeLabel.setText(_translate("MainWindow", "Time: 12:59:59", None))
        self.svLabel.setText(_translate("MainWindow", "SV: 999.9", None))
        self.pvLabel.setText(_translate("MainWindow", "PV: 999.9", None))
        self.startButton.setText(_translate("MainWindow", "Start", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.setSvButton.setText(_translate("MainWindow", "Set SV", None))
        self.baudComboBox.setItemText(0, _translate("MainWindow", "9600", None))
        self.baudComboBox.setItemText(1, _translate("MainWindow", "19200", None))
        self.baudComboBox.setItemText(2, _translate("MainWindow", "38400", None))
        self.baudComboBox.setItemText(3, _translate("MainWindow", "57600", None))
        self.baudComboBox.setItemText(4, _translate("MainWindow", "115200", None))
        self.label_13.setText(_translate("MainWindow", "Stop Bits:", None))
        self.label_14.setText(_translate("MainWindow", "Parity:", None))
        self.dataBitsComboBox.setItemText(0, _translate("MainWindow", "7", None))
        self.dataBitsComboBox.setItemText(1, _translate("MainWindow", "8", None))
        self.ParityComboBox.setItemText(0, _translate("MainWindow", "NONE", None))
        self.ParityComboBox.setItemText(1, _translate("MainWindow", "EVEN", None))
        self.ParityComboBox.setItemText(2, _translate("MainWindow", "ODD", None))
        self.label_15.setText(_translate("MainWindow", "Data Bits:", None))
        self.stopBitsComboBox.setItemText(0, _translate("MainWindow", "1", None))
        self.stopBitsComboBox.setItemText(1, _translate("MainWindow", "1.5", None))
        self.stopBitsComboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.connectButton.setText(_translate("MainWindow", "Connect RTU Modbus", None))
        self.label_16.setText(_translate("MainWindow", "Modbus Timeout", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connectionTab_2), _translate("MainWindow", "Connection", None))
        self.label.setText(_translate("MainWindow", "PV", None))
        self.getPvButton.setText(_translate("MainWindow", "Get PV", None))
        self.label_2.setText(_translate("MainWindow", "SV", None))
        self.getSvButton.setText(_translate("MainWindow", "Get SV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Readouts", None))
        self.dataTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monitorTab_2), _translate("MainWindow", "Monitor", None))
        item = self.DaqTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.DaqTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample#", None))
        item = self.DaqTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time(H:M:S)", None))
        item = self.DaqTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Datetime", None))
        item = self.DaqTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temperature", None))
        item = self.DaqTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Set Point", None))
        item = self.DaqTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Error", None))
        __sortingEnabled = self.DaqTableWidget.isSortingEnabled()
        self.DaqTableWidget.setSortingEnabled(False)
        item = self.DaqTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.DaqTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "00:00", None))
        item = self.DaqTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.DaqTableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.DaqTableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.DaqTableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "0", None))
        self.DaqTableWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox.setText(_translate("MainWindow", "Scroll to Bottom", None))
        self.label_3.setText(_translate("MainWindow", "# of Samples Taken: 00000", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab_2), _translate("MainWindow", "DAQ Viewer", None))
        self.label_4.setText(_translate("MainWindow", "Read Registers", None))
        self.label_17.setText(_translate("MainWindow", "PV Read Register", None))
        self.label_18.setText(_translate("MainWindow", "SV Read Register", None))
        self.label_19.setText(_translate("MainWindow", "PV Write Register", None))
        self.label_20.setText(_translate("MainWindow", "SV Write Register", None))
        self.label_5.setText(_translate("MainWindow", "Write Registers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.modbusTab_2), _translate("MainWindow", "ModBus Config", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExit.setText(_translate("MainWindow", "E&xit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the program", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the program", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionSave_Data.setText(_translate("MainWindow", "Save DAQ", None))
        self.actionSave_Data.setToolTip(_translate("MainWindow", "Save DAQ Data", None))
        self.actionSave_Data.setStatusTip(_translate("MainWindow", "Save DAQ Data", None))
        self.actionSave_Data.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionReset_DAQ.setText(_translate("MainWindow", "Reset DAQ", None))
        self.actionReset_DAQ.setToolTip(_translate("MainWindow", "Reset the DAQ", None))
        self.actionReset_DAQ.setStatusTip(_translate("MainWindow", "Reset the DAQ", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Help", None))

from PyQt4 import Qwt5
from guiqwt.plot import CurveWidget
import modMonUi_rc_rc
