# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ThirtySix\PycharmProjects\organization\package\tests\ui\tableTestUI.ui'
#
# Created: Wed Mar 16 12:43:01 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(813, 627)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.daqTableWidget = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.daqTableWidget.sizePolicy().hasHeightForWidth())
        self.daqTableWidget.setSizePolicy(sizePolicy)
        self.daqTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.daqTableWidget.setMidLineWidth(1)
        self.daqTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.daqTableWidget.setAlternatingRowColors(True)
        self.daqTableWidget.setObjectName(_fromUtf8("daqTableWidget"))
        self.daqTableWidget.setColumnCount(6)
        self.daqTableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.daqTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.daqTableWidget.setItem(0, 5, item)
        self.daqTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.daqTableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.daqTableWidget.horizontalHeader().setStretchLastSection(False)
        self.daqTableWidget.verticalHeader().setVisible(False)
        self.daqTableWidget.verticalHeader().setDefaultSectionSize(20)
        self.horizontalLayout_3.addWidget(self.daqTableWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.testDaqTableButton = QtGui.QPushButton(self.centralwidget)
        self.testDaqTableButton.setStatusTip(_fromUtf8(""))
        self.testDaqTableButton.setObjectName(_fromUtf8("testDaqTableButton"))
        self.verticalLayout_2.addWidget(self.testDaqTableButton)
        self.clearDaqButton = QtGui.QPushButton(self.centralwidget)
        self.clearDaqButton.setStatusTip(_fromUtf8(""))
        self.clearDaqButton.setObjectName(_fromUtf8("clearDaqButton"))
        self.verticalLayout_2.addWidget(self.clearDaqButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.sequenceTableWidget = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceTableWidget.sizePolicy().hasHeightForWidth())
        self.sequenceTableWidget.setSizePolicy(sizePolicy)
        self.sequenceTableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sequenceTableWidget.setMidLineWidth(1)
        self.sequenceTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.sequenceTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequenceTableWidget.setAlternatingRowColors(True)
        self.sequenceTableWidget.setColumnCount(2)
        self.sequenceTableWidget.setObjectName(_fromUtf8("sequenceTableWidget"))
        self.sequenceTableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.sequenceTableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sequenceTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sequenceTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sequenceTableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.sequenceTableWidget.setItem(0, 1, item)
        self.sequenceTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.sequenceTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.sequenceTableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.sequenceTableWidget.verticalHeader().setVisible(True)
        self.sequenceTableWidget.verticalHeader().setDefaultSectionSize(20)
        self.sequenceTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.sequenceTableWidget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sequenceStepsLabel = QtGui.QLabel(self.centralwidget)
        self.sequenceStepsLabel.setObjectName(_fromUtf8("sequenceStepsLabel"))
        self.gridLayout.addWidget(self.sequenceStepsLabel, 0, 0, 1, 1)
        self.sequenceLengthLabel = QtGui.QLabel(self.centralwidget)
        self.sequenceLengthLabel.setObjectName(_fromUtf8("sequenceLengthLabel"))
        self.gridLayout.addWidget(self.sequenceLengthLabel, 0, 1, 1, 1)
        self.maxTemperatureLabel = QtGui.QLabel(self.centralwidget)
        self.maxTemperatureLabel.setObjectName(_fromUtf8("maxTemperatureLabel"))
        self.gridLayout.addWidget(self.maxTemperatureLabel, 0, 2, 1, 1)
        self.startTimeDateLabel = QtGui.QLabel(self.centralwidget)
        self.startTimeDateLabel.setObjectName(_fromUtf8("startTimeDateLabel"))
        self.gridLayout.addWidget(self.startTimeDateLabel, 1, 0, 1, 1)
        self.endTimeDateLabel = QtGui.QLabel(self.centralwidget)
        self.endTimeDateLabel.setObjectName(_fromUtf8("endTimeDateLabel"))
        self.gridLayout.addWidget(self.endTimeDateLabel, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.addStepButton = QtGui.QPushButton(self.centralwidget)
        self.addStepButton.setObjectName(_fromUtf8("addStepButton"))
        self.verticalLayout_5.addWidget(self.addStepButton)
        self.removeStepButton = QtGui.QPushButton(self.centralwidget)
        self.removeStepButton.setObjectName(_fromUtf8("removeStepButton"))
        self.verticalLayout_5.addWidget(self.removeStepButton)
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.verticalLayout_5.addWidget(self.clearButton)
        self.timeDateButton = QtGui.QPushButton(self.centralwidget)
        self.timeDateButton.setObjectName(_fromUtf8("timeDateButton"))
        self.verticalLayout_5.addWidget(self.timeDateButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_8.addWidget(self.textEdit)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.heapyButton = QtGui.QPushButton(self.centralwidget)
        self.heapyButton.setStatusTip(_fromUtf8(""))
        self.heapyButton.setObjectName(_fromUtf8("heapyButton"))
        self.verticalLayout_4.addWidget(self.heapyButton)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.setStretch(0, 5)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Daq = QtGui.QAction(MainWindow)
        self.actionLoad_Daq.setObjectName(_fromUtf8("actionLoad_Daq"))
        self.actionSave_Daq = QtGui.QAction(MainWindow)
        self.actionSave_Daq.setObjectName(_fromUtf8("actionSave_Daq"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLoad_Program = QtGui.QAction(MainWindow)
        self.actionLoad_Program.setObjectName(_fromUtf8("actionLoad_Program"))
        self.actionSave_Program = QtGui.QAction(MainWindow)
        self.actionSave_Program.setObjectName(_fromUtf8("actionSave_Program"))
        self.menuFile.addAction(self.actionLoad_Daq)
        self.menuFile.addAction(self.actionSave_Daq)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Program)
        self.menuFile.addAction(self.actionSave_Program)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.daqTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.daqTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample#", None))
        item = self.daqTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time(H:M:S)", None))
        item = self.daqTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Datetime", None))
        item = self.daqTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temperature", None))
        item = self.daqTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Set Point", None))
        item = self.daqTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Error", None))
        __sortingEnabled = self.daqTableWidget.isSortingEnabled()
        self.daqTableWidget.setSortingEnabled(False)
        item = self.daqTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.daqTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "00:00", None))
        item = self.daqTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.daqTableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.daqTableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.daqTableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "0", None))
        self.daqTableWidget.setSortingEnabled(__sortingEnabled)
        self.testDaqTableButton.setToolTip(_translate("MainWindow", "Update the Readout", None))
        self.testDaqTableButton.setText(_translate("MainWindow", "Test DAQ Table", None))
        self.clearDaqButton.setToolTip(_translate("MainWindow", "Clear Program and Readout", None))
        self.clearDaqButton.setText(_translate("MainWindow", "Clear DAQ", None))
        item = self.sequenceTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.sequenceTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time (seconds)", None))
        item = self.sequenceTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Set Point", None))
        __sortingEnabled = self.sequenceTableWidget.isSortingEnabled()
        self.sequenceTableWidget.setSortingEnabled(False)
        item = self.sequenceTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.sequenceTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0", None))
        self.sequenceTableWidget.setSortingEnabled(__sortingEnabled)
        self.sequenceStepsLabel.setText(_translate("MainWindow", "Steps: 000", None))
        self.sequenceLengthLabel.setText(_translate("MainWindow", "Length: 00:00:00:000", None))
        self.maxTemperatureLabel.setText(_translate("MainWindow", "Max Step Temperature: 999.9", None))
        self.startTimeDateLabel.setText(_translate("MainWindow", "Start Time/Date: 12:59:59AM 12/04/2016", None))
        self.endTimeDateLabel.setText(_translate("MainWindow", "End Time/Date: 12:59:59AM 12/04/2016", None))
        self.addStepButton.setToolTip(_translate("MainWindow", "Add Step to Program", None))
        self.addStepButton.setStatusTip(_translate("MainWindow", "Add Step to Program", None))
        self.addStepButton.setText(_translate("MainWindow", "Add Step", None))
        self.removeStepButton.setToolTip(_translate("MainWindow", "Remove Step from Program", None))
        self.removeStepButton.setStatusTip(_translate("MainWindow", "Remove Step from Program", None))
        self.removeStepButton.setText(_translate("MainWindow", "Remove Step", None))
        self.clearButton.setToolTip(_translate("MainWindow", "Clear Program and Readout", None))
        self.clearButton.setStatusTip(_translate("MainWindow", "Clear Program and Readout", None))
        self.clearButton.setText(_translate("MainWindow", "Clear Program", None))
        self.timeDateButton.setText(_translate("MainWindow", "Set Start Time/Date", None))
        self.heapyButton.setToolTip(_translate("MainWindow", "Clear Program and Readout", None))
        self.heapyButton.setText(_translate("MainWindow", "Heapy", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Default UI", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Dark UI", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Fancy UI", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_Daq.setText(_translate("MainWindow", "Load DAQ", None))
        self.actionSave_Daq.setText(_translate("MainWindow", "Save DAQ", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionLoad_Program.setText(_translate("MainWindow", "Load Program", None))
        self.actionSave_Program.setText(_translate("MainWindow", "Save Program", None))

